import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import ClientLayout from "./clientLayout";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <ClientLayout>
          {children} <ToastContainer position="top-right" autoClose={3000} />
        </ClientLayout>
      </body>
    </html>
  );
}
